def get_keywords_Dic():
    """
    Returns a list of keywords used in the application.
    """
    return {
            "weather": [
                "current weather", "weather", "weather report", "weather update",
                "weather forecast", "today's weather", "today weather",
                "what's the weather", "how's the weather", "what's the temperature",
                "temperature outside", "is it raining", "do I need an umbrella",
                "weather conditions", "humidity level", "wind speed",
                "weather today", "weather right now", "is it sunny",
                "is it cold outside", "is it hot outside", "weather status",
                "tell me the weather", "check weather", "get weather", "what's it like outside",
                "how hot is it", "how cold is it", "will it rain today", "will it snow",
                "is it going to rain", "is it stormy", "current temperature", "outside temperature",
                "what's the forecast", "check forecast", "weather for today", "expected weather",
                "is it nice out", "is it windy", "wind conditions", "uv index",
                "air quality", "pollen count", "chance of rain", "chance of snow",
                "precipitation forecast", "feels like temperature", "real feel",
                "should I wear a jacket", "do I need a coat", "weather prediction",
                "local weather", "current conditions", "outdoor conditions", "sky conditions",
                "barometric pressure", "pressure reading", "dew point", "visibility",
                "cloud cover", "cloud conditions", "sunrise time", "sunset time",
                "weather outlook", "weekly forecast", "extended forecast", "hourly forecast",
                "tomorrow's weather", "weekend weather", "will it be nice today",
                "check if it's raining", "check if it's sunny", "get the temperature",
                "how humid is it", "what's the wind direction", "is there a storm coming",
                "weather alert", "weather warning", "severe weather", "is it foggy",
                "fog conditions", "heat index", "cold front", "warm front",
                "weather pattern", "weather trend", "is it going to be hot", "is it going to be cold",
                "is the sun out", "is it cloudy", "cloud status", "what's the low today",
                "what's the high today", "temperature range", "will I need sunscreen",
                "is it muggy outside", "what's the weather doing", "how's it looking outside",
                "tell me if it's raining", "give me the weather", "current weather status",
                "weather info", "check the sky", "what should I wear today", "weather check",
                "is it chilly", "is it freezing", "is it warm", "is it cool outside",
                "will it be hot later", "will it be cold later", "morning weather", "afternoon weather",
                "evening weather"
            ],
            "play_song": [
                "play song", "play music", "play some songs", "play my playlist",
                "shuffle songs", "play artist", "play album", "play track",
                "start music", "play my jam", "play my favorite song",
                "play something", "play beats", "play latest songs",
                "play relaxing music", "play workout music", "play study music",
                "play some tunes", "start a song", "hit the music", "crank the tunes",
                "drop some beats", "start the playlist", "queue up a song", "put on music",
                "play a hit", "stream some music", "spin some tracks", "play some audio",
                "start the stereo", "play the radio", "stream the radio", "play my favorites",
                "put on my mix", "shuffle my library", "play top hits", "play the charts",
                "play trending songs", "play recommended tracks", "play similar songs",
                "play that song I like", "find me a good song", "find some music",
                "play something upbeat", "play something chill", "play dance music",
                "play party music", "play background music", "play ambient sounds",
                "put on some jazz", "play classical music", "play rock music", "play pop songs",
                "play hip hop", "play rap songs", "play country music", "play folk songs",
                "play indie tracks", "play alternative music", "play electronic music",
                "play instrumental tracks", "play soundtrack", "play movie soundtrack",
                "play game soundtrack", "play karaoke tracks", "play sing-along songs",
                "play music for cooking", "play music for cleaning", "play focus music",
                "play concentration music", "play meditation music", "play yoga playlist",
                "play sleep sounds", "play white noise", "play nature sounds", "play rain sounds",
                "play ocean sounds", "play that new song", "play that old song",
                "continue playing music", "resume music", "unpause music", "continue playlist",
                "play next song", "play previous song", "play something different",
                "play something new", "play similar artists", "play this genre", "suggest some music",
                "what should I listen to", "surprise me with music", "play a random track",
                "play music from the 60s", "play music from the 70s", "play music from the 80s",
                "play music from the 90s", "play music from the 2000s", "play recent hits",
                "play classical piano", "play guitar music", "play drum solos", "play violin music",
                "play soundtrack music", "play theme songs", "play movie themes"
            ],
            "tasks": [
                "add task", "new task", "create task", "remember to",
                "add reminder", "add to my list", "note this down",
                "save this task", "task reminder", "set a task",
                "add to to-do", "create reminder", "schedule task",
                "make a note", "write this down", "don't let me forget",
                "remind me to", "put on my list", "add to agenda", "track this task",
                "save this for later", "note to self", "keep track of this", "log this task",
                "capture this item", "add an action item", "add to my planner", "schedule this",
                "add to calendar", "set deadline for", "mark as pending", "flag this item",
                "put this in my tasks", "add to my schedule", "make this a priority",
                "set reminder for tomorrow", "set reminder for later", "add to my projects",
                "create a new item", "add to my workflow", "put this in my inbox",
                "save for follow-up", "mark for review", "add to my checklist", "create a checklist item",
                "create a new to-do", "add action item", "put this on my radar", "keep this on my list",
                "remember this for me", "remind me about this", "alert me about this later",
                "add this to my tasks", "include this in my plan", "save this as a task",
                "record this activity", "document this task", "add this to my assignments",
                "make this a task", "set this as a goal", "add this objective", "track this project",
                "create a subtask", "add a dependent task", "create linked task", "add a milestone",
                "record this commitment", "save this obligation", "note this responsibility",
                "mark as important", "mark as urgent", "set as high priority", "flag as critical",
                "add to focus list", "add to today's agenda", "add to this week's plan",
                "schedule for next week", "add to monthly goals", "add to project plan",
                "create tracking item", "make this actionable", "set up recurring task",
                "add to daily checklist", "add to weekly review", "put in my task manager",
                "add with due date", "remind me on specific date", "set time-based reminder",
                "add location-based reminder", "add to shopping list", "add to grocery list",
                "add to errands list", "add to work tasks", "add to personal tasks",
                "add to home projects", "add to ideas list", "add to someday maybe list",
                "add to meeting agenda", "add to talking points"
            ],
            "speak_tasks": [
                "read my tasks", "what's on my list", "my reminders",
                "what do I have to do", "pending tasks", "say my to-dos",
                "current tasks", "upcoming tasks", "task status",
                "what's pending", "am I busy today", "do I have tasks",
                "tell me my tasks", "list my reminders", "what's on my plate",
                "what's on my agenda", "read my to-do list", "what should I be doing",
                "tell me what I need to do", "list my responsibilities", "list my obligations",
                "what are my priorities", "what's most important today", "what's my schedule",
                "run through my list", "go through my tasks", "summarize my to-dos",
                "give me my action items", "what items are pending", "what's still open",
                "what's not completed yet", "what have I missed", "what's outstanding",
                "what's overdue", "recite my tasks", "go over my reminders", "review my agenda",
                "check my calendar", "check my commitments", "what have I promised to do",
                "what deadlines do I have", "what's coming up", "what's next on my list",
                "what should I focus on", "what needs my attention", "what should I prioritize",
                "what tasks are critical", "what's urgent", "what's important but not urgent",
                "what can wait", "list my projects", "list my active tasks", "list tasks by priority",
                "list tasks by due date", "list tasks by project", "list tasks by category",
                "list personal tasks", "list work tasks", "list home tasks", "list shopping tasks",
                "list errands", "list items to buy", "list things to remember",
                "list appointments", "list meetings", "list calls to make", "list emails to send",
                "what do I need to prepare", "what do I need to finish", "what's almost due",
                "what's due today", "what's due this week", "what's due this month",
                "what's late", "what am I forgetting", "remind me what I planned",
                "remind me what I promised", "what's on my mind", "what did I note down",
                "tell me my notes", "recite my reminders", "read out my agenda",
                "tell me what's scheduled", "tell me my priorities", "tell me my goals",
                "what should I work on", "what needs completion", "what's in progress",
                "what have I started", "what needs finishing", "read off my checklist",
                "go through my plan", "what's on my roadmap", "what did I commit to"
            ],
            "show_tasks": [
                "show tasks", "display my list", "open reminders",
                "view my tasks", "task dashboard", "show to-dos",
                "pull up my list", "see my schedule", "task overview",
                "open task manager", "show planner", "display agenda",
                "show my to-do list", "bring up my tasks", "show me what I need to do",
                "display my reminders", "open my task list", "show my calendar",
                "visualize my tasks", "display my schedule", "show my priorities",
                "show my obligations", "show my task board", "display my kanban",
                "open my project view", "show me my goals", "display my milestones",
                "open my task tracker", "show me my progress", "display completion status",
                "show me what's pending", "display outstanding items", "show incomplete tasks",
                "display my urgent tasks", "show important tasks", "display my backlog",
                "open my weekly plan", "show my daily agenda", "display my monthly view",
                "show my yearly goals", "open my habit tracker", "show my routines",
                "display my commitments", "show my deadlines", "show overdue items",
                "display late tasks", "show upcoming deadlines", "display next actions",
                "show my waiting list", "display delegated tasks", "show assigned tasks",
                "display my accountability list", "show my projects", "display my areas",
                "show my categories", "display my contexts", "show my tags",
                "display my filtered view", "show my saved searches", "display smart lists",
                "show my custom views", "display my favorite tasks", "show my starred items",
                "display my flagged tasks", "show my focus list", "display my MIT's",
                "show my most important tasks", "display my big rocks", "show my key results",
                "display my objectives", "show my roadmap", "display my timeline",
                "show my Gantt chart", "display my dependencies", "show related tasks",
                "display my subtasks", "show my task hierarchy", "display my nested tasks",
                "show my task groups", "display my task clusters", "show my workflow",
                "display my process map", "show my system", "display my framework",
                "show my productivity tools", "display my organization system", "show my method",
                "display my task matrix", "show my quadrants", "display my task queue",
                "show my stack", "display my inbox", "show my capture list"
            ],
            "open_youtube": [
                "open youtube", "launch youtube", "go to youtube",
                "youtube.com", "watch videos", "show me youtube",
                "take me to youtube", "access youtube", "start youtube",
                "load youtube", "youtube please", "play youtube",
                "browse youtube", "visit youtube", "get youtube", "navigate to youtube",
                "bring up youtube", "pull up youtube", "view youtube", "display youtube",
                "enter youtube", "head to youtube", "move to youtube", "switch to youtube",
                "jump to youtube", "bring me to youtube", "let's go to youtube",
                "connect to youtube", "direct me to youtube", "route to youtube",
                "redirect to youtube", "let's watch youtube", "youtube app", "youtube website",
                "youtube portal", "youtube home", "youtube page", "youtube service",
                "youtube platform", "load the tube", "bring up video site", "open video sharing",
                "launch video platform", "open streaming site", "start video streaming",
                "launch video service", "open video host", "show me video content",
                "I want to watch videos", "I need youtube", "time for youtube",
                "can I see youtube", "let me watch youtube", "youtube now",
                "please show youtube", "I'd like youtube", "load video site",
                "get me to youtube", "connect to video service", "youtube time",
                "youtube videos please", "need to check youtube", "access video platform",
                "youtube access", "youtube connection", "youtube portal",
                "youtube homepage", "let's check youtube", "show youtube interface",
                "I want to browse videos", "open video library", "access video collection",
                "show me what's trending", "let's see popular videos", "open streaming platform",
                "launch video recommendations", "go to video subscriptions", "check my youtube feed",
                "see my youtube homepage", "open youtube trending", "go to youtube live",
                "pull up youtube music", "show youtube shorts", "access youtube studio",
                "open youtube premium", "check youtube notifications", "see youtube history",
                "open youtube search", "take me to youtube explore", "show youtube categories",
                "access youtube gaming", "go to youtube movies", "show youtube kids",
                "open youtube TV", "go to my youtube channel", "show me youtube originals",
                "access youtube learning", "open video platform"
            ],
            "bluetooth_on":[
                "turn on bluetooth", "enable bluetooth", "activate bluetooth",
                "start bluetooth", "bluetooth on", "switch on bluetooth",
                "power on bluetooth", "connect bluetooth", "make bluetooth discoverable",
                "turn bluetooth on", "enable my bluetooth", "activate my bluetooth",
                "start my bluetooth", "my bluetooth on", "switch my bluetooth on",
                "power my bluetooth on", "connect my bluetooth", "make my bluetooth discoverable",
                "bluetooth power on", "bluetooth activate", "bluetooth enable",
                "bluetooth start", "bluetooth switch on", "bluetooth turn on",
                "start bluetooth service", "enable bluetooth service", "activate bluetooth service",
                "turn on bluetooth service", "bluetooth service on", "bluetooth service start",
                "get bluetooth going", "fire up bluetooth", "initiate bluetooth",
                "begin bluetooth", "commence bluetooth", "start up bluetooth",
                "boot up bluetooth", "wake up bluetooth", "bring bluetooth online",
                "bring bluetooth up", "put bluetooth on", "set bluetooth on",
                "set bluetooth to on", "toggle bluetooth on", "flip bluetooth on",
                "bluetooth connection on", "bluetooth connectivity on", "bluetooth communications on",
                "start bluetooth connections", "enable bluetooth connections", "activate bluetooth connections",
                "turn on bluetooth connections", "bluetooth connections on", "make bluetooth available",
                "make bluetooth operational", "make bluetooth functional", "make bluetooth work",
                "make bluetooth active", "bluetooth activate now", "bluetooth on now",
                "bluetooth enable now", "bluetooth start now", "bluetooth turn on now",
                "I need bluetooth", "I want bluetooth", "I'd like bluetooth",
                "can you turn on bluetooth", "could you turn on bluetooth", "would you turn on bluetooth",
                "please turn on bluetooth", "turn the bluetooth on", "enable the bluetooth",
                "activate the bluetooth", "start the bluetooth", "the bluetooth on",
                "switch the bluetooth on", "power the bluetooth on", "connect the bluetooth",
                "make the bluetooth discoverable", "my device's bluetooth on", "device bluetooth on",
                "phone bluetooth on", "computer bluetooth on", "system bluetooth on",
                "internal bluetooth on", "external bluetooth on", "bluetooth radio on",
                "bluetooth chip on", "bluetooth hardware on", "bluetooth functionality on",
                "bluetooth capability on", "bluetooth feature on", "bluetooth option on"
            ],
            "bluetooth_off": [
                # Basic commands (20)
                "turn off bluetooth", "disable bluetooth", "deactivate bluetooth",
                "stop bluetooth", "bluetooth off", "switch off bluetooth",
                "power down bluetooth", "disconnect bluetooth", "hide bluetooth",
                "terminate bluetooth", "end bluetooth", "close bluetooth",
                "shut down bluetooth", "kill bluetooth", "cease bluetooth",
                "halt bluetooth", "pause bluetooth", "suspend bluetooth",
                "freeze bluetooth", "block bluetooth",
                
                # Privacy-focused (20)
                "make private", "go invisible", "become hidden",
                "stop discovery", "prevent pairing", "avoid connections",
                "block devices", "reject pairing", "deny connections",
                "refuse bluetooth", "decline links", "inhibit pairing",
                "restrict bluetooth", "forbid connections", "prohibit pairing",
                "veto bluetooth", "ban connections", "bar devices",
                "exclude pairing", "ostracize bluetooth",
                
                # Power saving (20)
                "save battery", "conserve power", "reduce energy",
                "lower consumption", "decrease drain", "minimize usage",
                "optimize power", "preserve battery", "extend life",
                "prolong charge", "cut bluetooth", "eliminate drain",
                "remove wireless", "drop connection", "shed bluetooth",
                "purge pairing", "clear links", "erase connections",
                "wipe bluetooth", "nullify pairing",
                
                # Security (20)
                "secure device", "lock down", "protect phone",
                "guard connections", "shield bluetooth", "defend pairing",
                "fortify device", "armor connections", "screen bluetooth",
                "filter pairing", "validate security", "authenticate first",
                "require pin", "demand password", "insist on verification",
                "necessitate approval", "mandate confirmation", "obligate screening",
                "compel authorization", "force validation",
                
                # Natural language (20)
                "can you turn bluetooth off", "please disable bluetooth",
                "would you deactivate bluetooth", "I need bluetooth off",
                "we should turn off bluetooth", "let's disable bluetooth",
                "mind turning off bluetooth", "could you switch bluetooth off",
                "would you mind deactivating bluetooth", "please make bluetooth hidden",
                "I'd like to stop bluetooth", "we need bluetooth disabled",
                "can we have bluetooth off", "please power down bluetooth",
                "would you stop bluetooth", "could you terminate bluetooth",
                "let's get bluetooth stopped", "can we turn bluetooth off",
                "please end bluetooth", "I want bluetooth deactivated"
            ],
            "open_application": [
                "open", "launch", "start", "run", "execute",
                "open the app", "launch this software", "start this application",
                "run this program", "open this software", "start an app",
                "launch an application", "turn on", "bring up",
                "fire up", "initiate", "get going", "boot up", "begin",
                "activate", "access", "pull up", "display", "show",
                "show me", "load", "load up", "call up", "invoke",
                "set up", "prepare", "get ready", "make ready", "commence",
                "kick off", "get started with", "let's open", "can you open",
                "please open", "would you open", "I need", "I want to use",
                "I'd like to open", "could you start", "please start", "go to",
                "navigate to", "switch to", "move to", "change to", "get me",
                "find me", "locate", "look for", "search for", "seek",
                "hunt down", "track down", "dig up", "uncover", "discover",
                "bring forth", "put forward", "advance", "progress", "proceed with",
                "carry on with", "continue with", "let's use", "use the",
                "utilize", "employ", "make use of", "work with", "operate",
                "handle", "manage", "engage with", "interact with", "deal with",
                "communicate with", "connect to", "link to", "get connected to",
                "establish connection with", "join with", "pair with", "couple with",
                "get hooked up to", "get linked to", "associate with", "could you launch",
                "please launch", "can you run", "please run", "would you run",
                "I'd like to run", "get me into", "take me to", "direct me to",
                "let me see", "show me the interface for", "provide access to",
                "grant entry to", "allow me into", "permit access to", "enable",
                "empower", "initialize", "originate", "generate", "produce", "create"
            ],"close_tab": [
                "close tab", "shut tab", "exit tab", "kill tab",
                "remove tab", "close page", "close window",
                "end tab", "terminate tab", "shutdown tab",
                "close browser tab", "exit webpage",
                "dismiss tab", "get rid of tab", "eliminate tab", "discard tab",
                "drop tab", "delete tab", "cancel tab", "abandon tab", "ditch tab",
                "lose tab", "dump tab", "scrap tab", "trash tab", "junk tab",
                "close this tab", "shut this tab", "exit this tab", "kill this tab",
                "remove this tab", "close this page", "close this window",
                "end this tab", "terminate this tab", "shutdown this tab",
                "close this browser tab", "exit this webpage", "dismiss this tab",
                "get rid of this tab", "eliminate this tab", "discard this tab",
                "drop this tab", "delete this tab", "cancel this tab", "abandon this tab",
                "ditch this tab", "lose this tab", "dump this tab", "scrap this tab",
                "trash this tab", "junk this tab", "close current tab", "shut current tab",
                "exit current tab", "kill current tab", "remove current tab", "close current page",
                "close current window", "end current tab", "terminate current tab",
                "shutdown current tab", "close current browser tab", "exit current webpage",
                "dismiss current tab", "get rid of current tab", "eliminate current tab",
                "discard current tab", "drop current tab", "delete current tab",
                "cancel current tab", "abandon current tab", "ditch current tab",
                "lose current tab", "dump current tab", "scrap current tab",
                "trash current tab", "junk current tab", "close that tab", "shut that tab",
                "exit that tab", "kill that tab", "remove that tab", "close that page",
                "close that window", "end that tab", "terminate that tab", "shutdown that tab",
                "close that browser tab", "exit that webpage", "dismiss that tab",
                "get rid of that tab", "eliminate that tab", "discard that tab",
                "drop that tab", "delete that tab", "cancel that tab", "abandon that tab",
                "ditch that tab", "lose that tab", "dump that tab", "scrap that tab",
                "trash that tab", "junk that tab"
            ],
            "close_application": [
                "close", "quit", "exit", "terminate",
                "shut down", "end program", "close window",
                "stop application", "kill app", "force quit",
                "close software", "exit program", "shutdown app",
                "end this", "finish this", "wrap this up", "conclude this",
                "stop this", "halt this", "abort this", "cancel this", "discontinue this",
                "cease this", "suspend this", "interrupt this", "break this off",
                "put an end to this", "bring this to a close", "draw this to a close",
                "bring this to an end", "wind this up", "finalize this", "complete this",
                "close this down", "shut this down", "power this down", "turn this off",
                "switch this off", "disable this", "deactivate this", "bring this down",
                "take this down", "remove this", "get rid of this", "dispose of this",
                "eliminate this", "end this session", "close this session", "finish this session",
                "terminate this session", "end this process", "close this process",
                "finish this process", "terminate this process", "end this application",
                "close this application", "finish this application", "terminate this application",
                "end this program", "close this program", "finish this program",
                "terminate this program", "end this software", "close this software",
                "finish this software", "terminate this software", "end this app",
                "close this app", "finish this app", "terminate this app",
                "shut down this program", "force close", "emergency exit", "quick close",
                "rapid shutdown", "immediate termination", "instant closure",
                "quick termination", "swift exit", "fast close", "prompt shutdown",
                "immediate close", "clean exit", "proper shutdown", "graceful exit",
                "safe close", "neat termination", "tidy shutdown", "orderly close",
                "organized exit", "methodical termination", "systematic shutdown",
                "regulated close", "controlled exit", "managed termination",
                "supervised shutdown", "overseen close", "guided exit"
            ],
            
            "wikipedia": [
                "wikipedia", "search wiki", "look up on wikipedia",
                "tell me about", "who is", "what is", "explain",
                "find on wikipedia", "wiki search", "information about",
                "details about", "background on", "history of",
                "wiki page for", "wikipedia entry", "wiki article", "wikipedia information",
                "wiki details", "find in encyclopedia", "encyclopedia search", "look up in wiki",
                "search for information about", "search for details about", "search for background on",
                "search for history of", "get me information about", "get me details about",
                "get me background on", "get me history of", "I want to know about",
                "I'd like to know about", "I need information on", "I need details on",
                "I need background on", "I need history of", "can you tell me about",
                "could you tell me about", "would you tell me about", "please tell me about",
                "can you explain", "could you explain", "would you explain", "please explain",
                "can you describe", "could you describe", "would you describe", "please describe",
                "can you give me information about", "could you give me information about",
                "would you give me information about", "please give me information about",
                "can you give me details about", "could you give me details about",
                "would you give me details about", "please give me details about",
                "can you give me background on", "could you give me background on",
                "would you give me background on", "please give me background on",
                "can you give me history of", "could you give me history of",
                "would you give me history of", "please give me history of",
                "what does wikipedia say about", "what's on wikipedia about",
                "what can I find on wikipedia about", "what will I find on wikipedia about",
                "what information is there on wikipedia about", "what details are there on wikipedia about",
                "what background is there on wikipedia about", "what history is there on wikipedia about",
                "search wikipedia for", "search the wiki for", "search the encyclopedia for",
                "look up information about", "find information about", "find details about",
                "find background on", "find history of", "discover information about",
                "discover details about", "discover background on", "discover history of",
                "learn about", "learn information about", "learn details about",
                "learn background on", "learn history of"
            ],
            "search_youtube": [
                "on youtube", "in youtube", "youtube search",
                "find on youtube", "look up on youtube",
                "search youtube for", "youtube lookup",
                "youtube query", "youtube results",
                "find videos about", "find videos of", "find videos on", "search videos for",
                "search videos of", "search videos on", "look for videos about",
                "look for videos of", "look for videos on", "video search for", "video search of",
                "video search on", "on youtube find", "on youtube search", "on youtube look for",
                "on youtube seek", "find in youtube", "search in youtube", "look in youtube",
                "seek in youtube", "check youtube for", "check on youtube for",
                "check in youtube for", "explore youtube for", "explore on youtube for",
                "explore in youtube for", "browse youtube for", "browse on youtube for",
                "browse in youtube for", "show me on youtube", "show me in youtube",
                "show me youtube results for", "find me on youtube", "find me in youtube",
                "find me youtube results for", "get me on youtube", "get me in youtube",
                "get me youtube results for", "youtube videos of", "youtube videos about",
                "youtube videos on", "youtube channel for", "youtube channel about",
                "youtube channel on", "youtube content for", "youtube content about",
                "youtube content on", "youtube footage of", "youtube footage about",
                "youtube footage on", "on youtube show me", "in youtube show me",
                "youtube search show me", "on youtube find me", "in youtube find me",
                "youtube search find me", "on youtube get me", "in youtube get me",
                "youtube search get me", "videos on youtube about", "videos in youtube about",
                "videos from youtube about", "clips on youtube about", "clips in youtube about",
                "clips from youtube about", "footage on youtube about", "footage in youtube about",
                "footage from youtube about", "youtube search results for", "youtube search results about",
                "youtube search results on", "youtube videos related to", "youtube videos concerning",
                "youtube videos regarding", "youtube content related to", "youtube content concerning",
                "youtube content regarding", "what does youtube have on", "what does youtube have about",
                "what does youtube have for", "what's on youtube about", "what's in youtube about",
                "what's from youtube about"
            ],
            "search_google": [
                "on google", "in google", "google search",
                "search google for", "look up on google",
                "find on google", "google results",
                "google lookup", "web search", "internet search",
                "search the web for", "search online for", "look up online",
                "web lookup", "internet lookup", "find online", "search the internet for",
                "online search", "browser search", "search engine lookup", "on the web find",
                "on the internet find", "online find", "google it", "google for me",
                "google this", "search for this", "find information for", "search information about",
                "look up information on", "find details on", "search details about",
                "look up details on", "search on google for", "search in google for",
                "find on google for", "find in google for", "look on google for",
                "look in google for", "google search for", "google search about",
                "google search on", "google find", "google find about", "google find on",
                "google look up", "google look up about", "google look up on",
                "web find", "web find about", "web find on", "web look up",
                "web look up about", "web look up on", "internet find", "internet find about",
                "internet find on", "internet look up", "internet look up about",
                "internet look up on", "online find", "online find about", "online find on",
                "online look up", "online look up about", "online look up on",
                "search results for", "search results about", "search results on",
                "google results for", "google results about", "google results on",
                "web results for", "web results about", "web results on",
                "internet results for", "internet results about", "internet results on",
                "online results for", "online results about", "online results on",
                "what does google say about", "what's on google about", "what's in google about",
                "what can I find on google about", "what will I find on google about",
                "what information is on google about", "what information is in google about",
                "what details are on google about", "what details are in google about",
                "search google and tell me about", "google search and tell me about",
                "find on google and tell me about", "look up on google and tell me about"
            ],
    "volume_up": [
        # Basic commands (20)
        "volume up", "increase volume", "louder", "turn up",
        "boost volume", "more volume", "higher volume",
        "volume increase", "amplify sound", "pump up the volume",
        "raise volume", "augment sound", "elevate audio",
        "intensify sound", "heighten volume", "escalate audio",
        "magnify sound", "enhance volume", "strengthen audio",
        "up the volume", "crank it up",
        
        # Incremental (20)
        "little louder", "bit higher", "slight increase",
        "moderate boost", "small raise", "tiny amplification",
        "minor augmentation", "gradual elevation", "step up",
        "nudge volume", "bump sound", "inch up",
        "gentle increase", "soft boost", "mild amplification",
        "measured raise", "controlled augmentation", "partial elevation",
        "fractional increase", "marginal boost",
        
        # Maximum (20)
        "full volume", "maximum sound", "all the way up",
        "to the top", "complete amplification", "total boost",
        "absolute maximum", "peak volume", "highest setting",
        "loudest possible", "unrestricted volume", "complete augmentation",
        "utter elevation", "supreme amplification", "ultimate boost",
        "extreme volume", "unlimited sound", "boundless amplification",
        "infinite volume", "absolute loudness",
        
        # Comparative (20)
        "louder than this", "more than current", "higher than now",
        "above current", "exceeding present", "surpassing this",
        "beyond current", "greater than now", "up from here",
        "over present", "plus some", "extra volume",
        "additional sound", "supplementary audio", "further amplification",
        "another notch", "one more level", "next step up",
        "increased level", "advanced volume",
        
        # Natural language (20)
        "can you increase volume", "please turn up sound",
        "would you make it louder", "I need more volume",
        "we should boost audio", "let's raise the volume",
        "mind amplifying sound", "could you augment audio",
        "would you mind elevating volume", "please enhance sound",
        "I'd like it louder", "we need higher volume",
        "can we have more sound", "please intensify audio",
        "would you amplify", "could you pump it up",
        "let's crank the volume", "can we go louder",
        "please strengthen sound", "I want increased volume"
    ],

    "volume_down": [
        # Basic commands (20)
        "volume down", "decrease volume", "quieter", "turn down",
        "reduce volume", "less volume", "lower volume",
        "volume decrease", "soften sound", "bring volume down",
        "diminish volume", "attenuate sound", "lower audio",
        "reduce sound", "lessen volume", "minimize audio",
        "dampen sound", "weaken volume", "moderate audio",
        "down the volume", "dial it back",
        
        # Incremental (20)
        "little quieter", "bit lower", "slight decrease",
        "moderate reduction", "small diminish", "tiny attenuation",
        "minor lowering", "gradual reduction", "step down",
        "nudge volume", "bump down", "inch down",
        "gentle decrease", "soft reduction", "mild attenuation",
        "measured lowering", "controlled reduction", "partial decrease",
        "fractional reduction", "marginal decrease",
        
        # Minimum (20)
        "lowest volume", "minimum sound", "all the way down",
        "to the bottom", "complete reduction", "total decrease",
        "absolute minimum", "quietest setting", "softest possible",
        "muted volume", "restricted volume", "complete attenuation",
        "utter reduction", "supreme decrease", "ultimate lowering",
        "extreme quiet", "limited sound", "boundless reduction",
        "infinite quiet", "absolute silence",
        
        # Comparative (20)
        "quieter than this", "less than current", "lower than now",
        "below current", "under present", "descending from this",
        "beneath current", "lesser than now", "down from here",
        "under present", "minus some", "reduced volume",
        "less sound", "diminished audio", "further reduction",
        "another notch down", "one more level down", "next step down",
        "decreased level", "receded volume",
        
        # Natural language (20)
        "can you decrease volume", "please turn down sound",
        "would you make it quieter", "I need less volume",
        "we should reduce audio", "let's lower the volume",
        "mind attenuating sound", "could you diminish audio",
        "would you mind reducing volume", "please soften sound",
        "I'd like it quieter", "we need lower volume",
        "can we have less sound", "please moderate audio",
        "would you decrease", "could you dial it back",
        "let's reduce the volume", "can we go quieter",
        "please weaken sound", "I want decreased volume"
    ],

    "mute": [
        # Basic commands (20)
        "mute", "silence", "no sound", "turn off sound",
        "kill volume", "sound off", "quiet mode",
        "disable audio", "shut sound", "mute all",
        "sound mute", "audio off", "volume zero",
        "no audio", "sound null", "mute sound",
        "silent mode", "no noise", "zero volume",
        "complete mute", "total silence",
        
        # Temporary (20)
        "mute temporarily", "quiet briefly", "silence for now",
        "no sound temporarily", "turn off audio momentarily",
        "kill volume briefly", "sound off for a bit",
        "disable audio temporarily", "shut sound shortly",
        "mute all for now", "sound mute temporarily",
        "audio off briefly", "volume zero for a while",
        "no audio temporarily", "sound null for now",
        "mute sound shortly", "silent mode temporarily",
        "no noise for a bit", "zero volume momentarily",
        "complete mute briefly", "total silence temporarily",
        
        # Device-specific (20)
        "mute phone", "silence computer", "no sound on tv",
        "turn off speaker audio", "kill headphones volume",
        "sound off on device", "quiet system",
        "disable device audio", "shut phone sound",
        "mute all speakers", "sound mute on tv",
        "audio off on computer", "volume zero on phone",
        "no audio from speakers", "sound null on device",
        "mute sound system", "silent mode on tv",
        "no noise from computer", "zero volume on speakers",
        "complete mute device", "total silence system",
        
        # Application-specific (20)
        "mute video", "silence call", "no sound in game",
        "turn off music audio", "kill video volume",
        "sound off in app", "quiet media",
        "disable player audio", "shut movie sound",
        "mute all videos", "sound mute in call",
        "audio off in game", "volume zero in app",
        "no audio from media", "sound null in player",
        "mute sound in video", "silent mode in call",
        "no noise in game", "zero volume in media",
        "complete mute application", "total silence player",
        
        # Natural language (20)
        "can you mute", "please silence sound",
        "would you turn off audio", "I need no sound",
        "we should mute", "let's go silent",
        "mind killing volume", "could you disable audio",
        "would you mind muting", "please shut sound",
        "I'd like it muted", "we need no audio",
        "can we have silence", "please quiet mode",
        "would you mute all", "could you sound off",
        "let's mute everything", "can we go silent",
        "please no noise", "I want complete silence"
    ],

    "unmute": [
        # Basic commands (20)
        "unmute", "sound on", "enable audio", "restore volume",
        "turn on sound", "audio on", "hear again",
        "reactivate sound", "bring back sound", "volume on",
        "sound unmute", "audio enable", "volume restore",
        "sound return", "audio reactivate", "unmute sound",
        "normal mode", "sound normal", "volume back",
        "complete unmute", "total sound restore",
        
        # Level-specific (20)
        "unmute to low", "sound on quiet", "enable audio softly",
        "restore volume gently", "turn on sound moderately",
        "audio on slightly", "hear again faintly", "reactivate sound partially",
        "bring back sound somewhat", "volume on minimally",
        "sound unmute to half", "audio enable to quarter",
        "volume restore to 30%", "sound return to 40%",
        "audio reactivate to 50%", "unmute sound to 60%",
        "normal mode at 70%", "sound normal at 80%",
        "volume back to 90%", "complete unmute fully",
        
        # Device-specific (20)
        "unmute phone", "sound on computer", "enable tv audio",
        "restore speaker volume", "turn on headphones sound",
        "audio on device", "hear system again",
        "reactivate phone sound", "bring back speaker audio",
        "volume on tv", "sound unmute on computer",
        "audio enable on phone", "volume restore on device",
        "sound return on speakers", "audio reactivate on tv",
        "unmute sound system", "normal mode on computer",
        "sound normal on phone", "volume back on speakers",
        "complete unmute device", "total sound restore system",
        
        # Application-specific (20)
        "unmute video", "sound on call", "enable game audio",
        "restore music volume", "turn on movie sound",
        "audio on app", "hear media again",
        "reactivate video sound", "bring back call audio",
        "volume on game", "sound unmute in player",
        "audio enable in app", "volume restore in media",
        "sound return in call", "audio reactivate in game",
        "unmute sound in video", "normal mode in app",
        "sound normal in player", "volume back in media",
        "complete unmute application", "total sound restore player",
        
        # Natural language (20)
        "can you unmute", "please turn sound on",
        "would you enable audio", "I need sound back",
        "we should unmute", "let's hear again",
        "mind restoring volume", "could you reactivate audio",
        "would you mind unmuting", "please bring back sound",
        "I'd like it unmuted", "we need audio on",
        "can we have sound", "please enable audio",
        "would you unmute all", "could you sound on",
        "let's unmute everything", "can we hear again",
        "please restore sound", "I want audio back"
    ],

    "current_volume": [
        # Basic queries (20)
        "current volume", "volume level", "what's the volume",
        "how loud is it", "volume status", "sound level",
        "volume setting", "audio level", "check volume",
        "volume percentage", "is it muted", "volume query",
        "sound measurement", "audio status", "volume check",
        "loudness level", "current decibel", "sound intensity",
        "audio output level", "volume reading",
        
        # Comparative (20)
        "is volume high", "is sound low", "how high is volume",
        "how low is audio", "what percent is volume",
        "where is volume set", "what's current loudness",
        "is audio at max", "is sound at min", "is volume medium",
        "is it halfway", "is sound quarter", "is volume three quarters",
        "is audio muted", "is sound on", "is volume off",
        "how much louder", "how much quieter", "what volume step",
        "which volume notch",
        
        # Device-specific (20)
        "phone volume", "computer sound level", "tv audio status",
        "speaker volume", "headphones loudness", "device audio",
        "system volume", "mobile sound", "tablet audio level",
        "laptop volume", "desktop sound", "monitor audio",
        "smart speaker volume", "soundbar level", "home theater audio",
        "car stereo volume", "bluetooth speaker sound",
        "wireless headphones audio", "gaming headset volume",
        "external speaker level",
        
        # Application-specific (20)
        "video volume", "call sound level", "game audio status",
        "music volume", "movie loudness", "app audio",
        "media volume", "player sound", "stream audio level",
        "browser volume", "conference sound", "meeting audio",
        "presentation volume", "voice chat level", "video call audio",
        "recording volume", "playback sound", "notification audio",
        "alarm volume", "ringtone level",
        
        # Natural language (20)
        "can you check volume", "please tell me sound level",
        "would you report audio status", "I need volume information",
        "we should know loudness", "let's check audio level",
        "mind telling volume", "could you state sound level",
        "would you mind checking audio", "please inform volume",
        "I'd like volume status", "we need sound information",
        "can we have audio level", "please report volume",
        "would you check sound", "could you verify audio",
        "let's confirm volume", "can we know loudness",
        "please tell current volume", "I want sound level"
    ],

    "battery_status": [
        # Basic queries (20)
        "battery status", "battery level", "how much battery",
        "power status", "charge level", "remaining battery",
        "battery percentage", "how's my battery", "battery info",
        "is it charging", "power percentage", "battery health",
        "charge status", "power level", "battery condition",
        "remaining charge", "current battery", "battery state",
        "power remaining", "battery capacity",
        
        # Percentage-specific (20)
        "what percent battery", "how many percent left",
        "what's battery percentage", "give me battery percent",
        "show charge percentage", "display power percentage",
        "current charge percent", "remaining battery percent",
        "how much percent battery", "what's my battery percentage",
        "tell me charge percent", "report battery percentage",
        "state power percentage", "declare charge percent",
        "announce battery percent", "communicate power percentage",
        "indicate charge percent", "specify battery percentage",
        "detail power percent", "present charge percentage",
        
        # Time-based (20)
        "battery time left", "how long battery last",
        "remaining battery time", "time until dead",
        "hours left on battery", "minutes remaining",
        "battery duration", "power duration", "charge lifespan",
        "usage time left", "operation time remaining",
        "active time left", "standby time remaining",
        "screen-on time left", "estimated time remaining",
        "projected battery life", "calculated power duration",
        "predicted charge time", "forecasted battery life",
        "anticipated power remaining",
        
        # Charging-status (20)
        "is it plugged in", "am I charging", "charging status",
        "power source", "connected to power", "on battery",
        "off charger", "charging or not", "plugged or unplugged",
        "ac power status", "dc power status", "usb power",
        "wireless charging", "fast charging", "slow charging",
        "not charging", "fully charged", "partially charged",
        "almost charged", "just plugged in",
        
        # Natural language (20)
        "can you check battery", "please tell me power status",
        "would you report charge level", "I need battery information",
        "we should know power level", "let's check charge status",
        "mind telling battery", "could you state power level",
        "would you mind checking charge", "please inform battery",
        "I'd like power status", "we need charge information",
        "can we have battery level", "please report power",
        "would you check charge", "could you verify battery",
        "let's confirm power", "can we know charge level",
        "please tell current battery", "I want power status"
    ],

    "brightness_up": [
        # Basic commands (20)
        "brightness up", "increase brightness", "brighter",
        "more light", "turn up brightness", "boost brightness",
        "enhance display", "make it brighter", "screen brighter",
        "brighten up", "more luminance", "higher brightness",
        "augment illumination", "elevate luminosity", "intensify light",
        "heighten radiance", "escalate glow", "magnify shine",
        "strengthen brilliance", "up the brightness",
        
        # Incremental (20)
        "little brighter", "bit higher", "slight increase",
        "moderate boost", "small raise", "tiny enhancement",
        "minor augmentation", "gradual elevation", "step up",
        "nudge brightness", "bump light", "inch up",
        "gentle increase", "soft boost", "mild enhancement",
        "measured raise", "controlled augmentation", "partial elevation",
        "fractional increase", "marginal boost",
        
        # Maximum (20)
        "full brightness", "maximum light", "all the way up",
        "to the top", "complete enhancement", "total boost",
        "absolute maximum", "peak brightness", "highest setting",
        "brightest possible", "unrestricted brightness", "complete augmentation",
        "utter elevation", "supreme enhancement", "ultimate boost",
        "extreme brightness", "unlimited light", "boundless enhancement",
        "infinite brightness", "absolute illumination",
        
        # Comparative (20)
        "brighter than this", "more than current", "higher than now",
        "above current", "exceeding present", "surpassing this",
        "beyond current", "greater than now", "up from here",
        "over present", "plus some", "extra brightness",
        "additional light", "supplementary illumination", "further enhancement",
        "another notch", "one more level", "next step up",
        "increased level", "advanced brightness",
        
        # Natural language (20)
        "can you increase brightness", "please turn up display",
        "would you make it brighter", "I need more light",
        "we should boost brightness", "let's raise the luminosity",
        "mind enhancing display", "could you augment illumination",
        "would you mind elevating brightness", "please enhance screen",
        "I'd like it brighter", "we need higher brightness",
        "can we have more light", "please intensify display",
        "would you amplify brightness", "could you pump it up",
        "let's crank the brightness", "can we go brighter",
        "please strengthen light", "I want increased brightness"
    ],

    "brightness_down": [
        # Basic commands (20)
        "brightness down", "decrease brightness", "dimmer",
        "less light", "turn down brightness", "reduce brightness",
        "dim display", "make it darker", "screen dimmer",
        "darken screen", "less luminance", "lower brightness",
        "diminish illumination", "reduce luminosity", "soften light",
        "lessen radiance", "descend glow", "dampen shine",
        "weaken brilliance", "down the brightness",
        
        # Incremental (20)
        "little dimmer", "bit lower", "slight decrease",
        "moderate reduction", "small diminish", "tiny softening",
        "minor reduction", "gradual descent", "step down",
        "nudge brightness", "bump down", "inch down",
        "gentle decrease", "soft reduction", "mild dimming",
        "measured descent", "controlled reduction", "partial decrease",
        "fractional reduction", "marginal decrease",
        
        # Minimum (20)
        "lowest brightness", "minimum light", "all the way down",
        "to the bottom", "complete reduction", "total decrease",
        "absolute minimum", "darkest setting", "dimest possible",
        "night mode", "restricted brightness", "complete softening",
        "utter reduction", "supreme decrease", "ultimate dimming",
        "extreme darkness", "limited light", "boundless reduction",
        "infinite dimness", "absolute darkness",
        
        # Comparative (20)
        "dimmer than this", "less than current", "lower than now",
        "below current", "under present", "descending from this",
        "beneath current", "lesser than now", "down from here",
        "under present", "minus some", "reduced brightness",
        "less light", "diminished illumination", "further reduction",
        "another notch down", "one more level down", "next step down",
        "decreased level", "receded brightness",
        
        # Natural language (20)
        "can you decrease brightness", "please turn down display",
        "would you make it dimmer", "I need less light",
        "we should reduce brightness", "let's lower the luminosity",
        "mind dimming display", "could you soften illumination",
        "would you mind reducing brightness", "please darken screen",
        "I'd like it dimmer", "we need lower brightness",
        "can we have less light", "please moderate display",
        "would you decrease brightness", "could you dial it back",
        "let's reduce the brightness", "can we go dimmer",
        "please weaken light", "I want decreased brightness"
    ]
                }